CREATE TABLE IF NOT EXISTS pet_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL UNIQUE,
  nickname VARCHAR(20) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_post (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(500) NOT NULL,
  cover_image VARCHAR(255) NOT NULL,
  cover_thumb_url VARCHAR(255) NOT NULL,
  images JSON NOT NULL,
  like_count INT DEFAULT 0,
  collect_count INT DEFAULT 0,
  comment_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content VARCHAR(200) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_like (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0,
  UNIQUE KEY uk_user_post_like (user_id, post_id, is_deleted)
);

CREATE TABLE IF NOT EXISTS pet_collect (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0,
  UNIQUE KEY uk_user_post_collect (user_id, post_id, is_deleted)
);

CREATE TABLE IF NOT EXISTS pet_fortune (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  level VARCHAR(20) NOT NULL,
  content VARCHAR(255) NOT NULL,
  day_index TINYINT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_checkin (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  checkin_date DATE NOT NULL,
  fortune_id BIGINT NOT NULL,
  points_earned INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0,
  UNIQUE KEY uk_user_checkin (user_id, checkin_date, is_deleted)
);

CREATE TABLE IF NOT EXISTS pet_notification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  type VARCHAR(30) NOT NULL,
  content VARCHAR(255) NOT NULL,
  related_id BIGINT DEFAULT 0,
  is_read TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_points (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  total_points INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pet_points_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  source VARCHAR(30) NOT NULL,
  amount INT NOT NULL,
  remark VARCHAR(255) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT 0,
  updated_by BIGINT DEFAULT 0,
  is_deleted TINYINT(1) DEFAULT 0
);
